### ISSUE TITLE
`store_dart_post_cobject`'s `ptr` parameter has wrong bool type

### ISSUE THREAD

**Issue by Omnissi** [Desdaemon/flutter_rust_bridge_template#11]
Hello!

I am getting an error when I try to build the project:

`lib/bridge_generated.dart(151,27): error GA89667EF: The parameter 'ptr' of the method 'NativeWire.store_dart_post_cobject' has type 'Pointer<NativeFunction<Uint8 Function(Int64, Pointer<Void>)>>', which does not match the corresponding type, 'Pointer<NativeFunction<Bool Function(Int64, Pointer<Void>)>>', in the overridden method, 'FlutterRustBridgeWireBase.store_dart_post_cobject'. [G:\Work\flutter\flutter_rust_bridge_template\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(240,5): error MSB8066: ���짮��⥫�᪠� ᡮઠ ��� "G:\Work\flutter\flutter_rust_bridge_template\build\windows\CMakeFiles\f7371cd34616b60b3445bd875005fe78\flutter_windows.dll.rule;G:\Work\flutter\flutter_rust_bridge_template\build\windows\CMakeFiles\8d5a0b7881d245aedd6fc5482e6722a4\flutter_assemble.rule" �����訫� ࠡ��� � ����� 1. [G:\Work\flutter\flutter_rust_bridge_template\build\windows\flutter\flutter_assemble.vcxproj]`

Flutter SDK 3.0.4
Commit [440817e](https://github.com/Desdaemon/flutter_rust_bridge_template/commit/440817e6291212049344cbc07192139660447d29)

**Comment by Desdaemon** [comment]
This is most like related to the ffigen 6.0 issue, please try `dart pub global activate ffigen` again or see [this issue](https://github.com/fzyzcjy/flutter_rust_bridge/issues/478)

**Comment by Omnissi** [comment]
Unfortunately it didn't help.
And yes I downgraded ffigen to 5.

**Comment by Desdaemon** [comment]
I ran into this issue myself, `flutter pub upgrade` and upgrading to ffigen v6 did the trick.
