### ISSUE TITLE
Couldn't get the template to run

### ISSUE THREAD

**Issue by Roms1383** [Desdaemon/flutter_rust_bridge_template#12]
Hi, I couldn't get the template to run neither on my phone nor my laptop.
I've already spent a couple of hours to install more versions of Android SDK/NDK, triple-check my binaries paths, so on and so forth. I've currently reached a peak of frustration so I finally resigned myself to come check for some help. And I'm sorry because I already bothered @fzyzcjy with a similar setup issue many months ago.

So here are the issues I ran into:

<details><summary>on my phone</summary>

Launching lib/main.dart on SM G955F in debug mode...
[2022-07-24T10:30:06Z INFO  cargo_ndk::cli] Using NDK at path: /Users/romain/Library/Android/sdk/ndk/25.0.8775105
[2022-07-24T10:30:06Z INFO  cargo_ndk::cli] NDK API level: 21
[2022-07-24T10:30:06Z INFO  cargo_ndk::cli] Building targets: armeabi-v7a, arm64-v8a, x86, x86_64
[2022-07-24T10:30:06Z INFO  cargo_ndk::cli] Building armeabi-v7a (armv7-linux-androideabi)
   Compiling native v0.1.0 (/Users/romain/Development/lab/cerclo-app/native)
error: linking with `/Users/romain/Library/Android/sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang` failed: exit status: 1
  |
  = note: "/Users/romain/Library/Android/sdk/ndk/25.0.8775105/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang" "-Wl,--version-script=/var/folders/st/8cddrx857yj1gh8yvj0j499c0000gn/T/rustcxZ5dAB/list" "-march=armv7-a" "/var/folders/st/8cddrx857yj1gh8yvj0j499c0000gn/T/rustcxZ5dAB/symbols.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.122iwb5z1t50cuvc.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.177diwzl93c55oy1.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.1cd5yo1icoxyg0p2.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.1er713l1aptgams.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.1mzofwlno4pkn0ls.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.1qeaxvhrovxwqehu.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.1ws413k6xyr7sm2r.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.1xtoau7nb5ryg583.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.22h2wk361l0i6k3.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.2dr3mxma6g65fd79.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.2eig1t929jxooor6.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.2ezjy39e1jfoyru6.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.2mi8kmrewv1beygh.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.2mqw1yvbndvf7843.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.2mzvio6g86oq4wp3.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.2nswevbyxnmp42cz.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.2pixx6e0ipwrv8yl.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.2tg8rdutovcororn.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.2w9hv8n0643mxt3z.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.30jiie4jjkuaplgd.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.3235q596o5dblbfv.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.34lgp904l703whe4.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.37iii23muijq59ii.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.39gyp2nifc5upujc.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.3cr2063nfha16pn0.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.3vng5ql34afz6f32.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.3xl9wje8kkjsikky.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.48ghwwoilwdjfr9g.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.4qi5jp92qlqr9lk3.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.4sj0jopa237ad9lt.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.4u52lwczimui7z6l.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.4xc7whtaf3kipbhs.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.50137tfwukmlusdv.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.50aepczn7lvv2lh2.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.5238jxxju15se1y8.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.59uyrwrf6dtl4jhg.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.ho85uht6rvzf3wr.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.hr86jsp0cgxyhdm.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.jxdvb8yseu0mmsc.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.lfuvrodfamwk2zl.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.sh526vr8qiystdk.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.upy4majzgoflcyl.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.v15itprdctsl5g9.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.vt232r5ogzvchfs.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.yb02zeol6bs1q8u.rcgu.o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/native.4c56d4lf6ao1urmm.rcgu.o" "-Wl,--as-needed" "-L" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps" "-L" "/Users/romain/Development/lab/cerclo-app/native/target/debug/deps" "-L" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib" "-Wl,-Bstatic" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/libflutter_rust_bridge-e99aab9d091af425.rlib" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/libthreadpool-5893d6078afe1b8d.rlib" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/libnum_cpus-f7deb8810ace57e1.rlib" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/libparking_lot-d6fe50d2c6e86a20.rlib" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/libparking_lot_core-eb134ae4ea784d3a.rlib" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/liblibc-3f0d30e8bd4d33d1.rlib" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/libcfg_if-53681c17a9da6a2f.rlib" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/libsmallvec-71d8973e1f10ad26.rlib" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/liblock_api-de0384fdaa7394fa.rlib" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/libscopeguard-accd7bc777b14ea4.rlib" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/liblazy_static-ac577c243c3b4cd9.rlib" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/libanyhow-78665c59bc55a175.rlib" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/liballo_isolate-f4fbb6580f45988b.rlib" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/libatomic-c01ecc833d0ba579.rlib" "-Wl,--start-group" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libstd-9d30f594056196c1.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libpanic_unwind-3d3501cd0b1259c4.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libobject-0384f716e625bcf1.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libmemchr-e27b960fd5627dab.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libaddr2line-4ad62b9d84d086e3.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libgimli-ddb8f984ed27ae53.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/librustc_demangle-5051f256cfabb252.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libstd_detect-8097ccf7f015ca46.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libhashbrown-df465ae263b4530f.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libminiz_oxide-9f01fc15e55b0908.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libadler-ab296d158dc44ed8.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/librustc_std_workspace_alloc-8b1e20903199ead7.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libunwind-7d252cb2e4c7ed47.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libcfg_if-d25ced404ae876aa.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/liblibc-c7445088b4a180fb.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/liballoc-3208c74083ce8272.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/librustc_std_workspace_core-5120ad6ce2c747fb.rlib" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libcore-ec957a011fb606d5.rlib" "-Wl,--end-group" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib/libcompiler_builtins-c622d88c2d8b76db.rlib" "-Wl,-Bdynamic" "-ldl" "-llog" "-lgcc" "-ldl" "-lc" "-lm" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/Users/romain/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/armv7-linux-androideabi/lib" "-o" "/Users/romain/Development/lab/cerclo-app/native/target/armv7-linux-androideabi/debug/deps/libnative.so" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro,-znow" "-nodefaultlibs"
  = note: ld: error: unable to find library -lgcc
          clang-14: error: linker command failed with exit code 1 (use -v to see invocation)

error: could not compile `native` due to previous error
[2022-07-24T10:30:07Z INFO  cargo_ndk::cli] If the build failed due to a missing target, you can run this command:
[2022-07-24T10:30:07Z INFO  cargo_ndk::cli] 
[2022-07-24T10:30:07Z INFO  cargo_ndk::cli]     rustup target install armv7-linux-androideabi

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:cargoBuildDebug'.
> Process 'command 'sh'' finished with non-zero exit value 101

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Running Gradle task 'assembleDebug'...                              8.5s
Exception: Gradle task assembleDebug failed with exit code 1

</details>

> but thing is, `armv7-linux-androideabi` is already installed on my machine, as you can see below

<details><summary>on my laptop</summary>

Multiple devices found:
macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
Chrome (web)    • chrome • web-javascript • Google Chrome 103.0.5060.134
[1]: macOS (macos)
[2]: Chrome (chrome)
Please choose one (To quit, press "q/Q"): 1
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-001218103438801E }
{ platform:macOS, arch:x86_64, id:00006000-001218103438801E }
clang: error: no such file or directory: 'native.dylib'
Command Ld failed with a nonzero exit code
** BUILD FAILED **

Building macOS application...                                           
Exception: Build process failed

</details>

> this one I'm not quite sure why ...

The only thing I've modified from the template so far is this:

<img width="1495" alt="diff-template" src="https://user-images.githubusercontent.com/21016014/180643410-c6e16626-1e23-4177-a84d-dd3b73bc69df.png">

Here are the details of my setup, I tried to be as exhaustive as possible but please do let me know if something of importance is missing.

<details><summary>about my computer</summary>

<img width="217" alt="my-laptop" src="https://user-images.githubusercontent.com/21016014/180643954-93e49d49-9bd5-415b-be6b-9c8092366fbc.png">

</details>

<details><summary>flutter devices</summary>

3 connected devices:

SM G955F (mobile) • ce061716aaf37cd40d • android-arm64  • Android 9 (API 28)
macOS (desktop)   • macos              • darwin-arm64   • macOS 12.4 21F79 darwin-arm
Chrome (web)      • chrome             • web-javascript • Google Chrome 103.0.5060.134

</details>

<details><summary>flutter doctor -v</summary>

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.4 21F79 darwin-arm, locale en-TH)
    • Flutter version 3.0.5 at /Users/romain/Development/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (10 days ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/romain/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.69.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • SM G955F (mobile) • ce061716aaf37cd40d • android-arm64  • Android 9 (API 28)
    • macOS (desktop)   • macos              • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 103.0.5060.134

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

</details>

<details><summary>echo $ANDROID_NDK</summary>

/Users/romain/Library/Android/sdk

</details>

<details><summary>echo $ANDROID_NDK_HOME</summary>

/Users/romain/Library/Android/sdk

</details>

<details><summary>rustup target install armv7-linux-androideabi</summary>

info: component 'rust-std' for target 'armv7-linux-androideabi' is up to date

</details>

<details><summary>brew info llvm</summary>

llvm: stable 14.0.6 (bottled), HEAD [keg-only]
Next-gen compiler infrastructure
https://llvm.org/
/opt/homebrew/Cellar/llvm/14.0.6_1 (5,851 files, 983.5MB)
  Poured from bottle on 2022-07-23 at 11:38:19
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/llvm.rb
License: Apache-2.0 with LLVM-exception
==> Dependencies
Build: cmake ✔, swig ✔
Required: python@3.10 ✔

</details>

<details><summary>dart pub global activate ffigen</summary>

Package ffigen is currently active at version 6.0.1.
The package ffigen is already activated at newest available version.
To recompile executables, first run `dart pub global deactivate ffigen`.
Activated ffigen 6.0.1.

</details>

<details><summary>which clang</summary>

/usr/bin/clang

</details>

<details><summary>clang -v</summary>

Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

</details>

Any help would be very much appreciated, because I tend to suxxx at solving build issues 😅

**Comment by Desdaemon** [comment]
No problem. I think the problem is here:

> Library/Android/sdk/ndk/25.0.87

It's been a while but AFAIK NDK versions past 22 are still not supported by Rust. As time goes by it will be harder to obtain this specific version of NDK, and I would much love to see changes in this regard as well.

**Comment by Roms1383** [comment]
@Desdaemon you really rock !! Indeed as soon as I uninstalled all versions except NDK 22 everything build very fine on mobile. The error on desktop app is still here though, so if you have any hint or advice I'll gladly follow it.
But at least, I get it to run on mobile so I can call it a day :)

**Comment by Desdaemon** [comment]
I'll have a look at the desktop issue soon, but glad to hear it's working!
