### ISSUE TITLE
Unclear role of bridge_definitions.dart 

### ISSUE THREAD

**Issue by gjf2a** [Desdaemon/flutter_rust_bridge_template#19]
The template itself worked for me just fine as written. However, when I modified `api.rs`, reran `flutter_rust_bridge_codegen`, and recompiled the Rust code, I got numerous compilation errors along the following lines:

```
lib/ffi.dart:8:1: Error: 'Native' is exported from both 'package:flutter_rust_bridge_template/bridge_generated.dart' and 'package:flutter_rust_bridge_template/bridge_definitions.dart'.
export 'bridge_definitions.dart';
```

My call to `flutter_rust_bridge_codegen` was:

```
flutter_rust_bridge_codegen --rust-input native\src\api.rs --dart-output .\lib\bridge_generated.dart
```

Part of the reason for this error, I suppose, is that `flutter_rust_bridge_codegen` did not generate a new `bridge_definitions.dart` file.  I can see why, given the above command. But as I was following the example from [the quickstart section](http://cjycode.com/flutter_rust_bridge/quickstart.html) of [the book](http://cjycode.com/flutter_rust_bridge/index.html), it is not at all clear what else should have been done there.

I fixed the problem by deleting `bridge_definitions.dart` and removing these two lines from `ffi.dart`:

```
import 'bridge_definitions.dart';
export 'bridge_definitions.dart';
```

At that point, I was able to `flutter run` my modified app perfectly well.

I would be happy to make a pull request to update the template repository with the above changes, but I fear I am overlooking something important. Because my code works, I have no idea what that is.

**Comment by Desdaemon** [comment]
No problem!

The bridge_definitions file is embedded into the bridge file if you didn't specify `--dart-decl-output` when running codegen. It is only more prominent now because it is required for now when passing `--wasm`. The template will probably continue to emit code for WASM for a good out-of-the-box experience however.

**Comment by gjf2a** [comment]
Ok, cool, thanks for the clarification! I created a pull request to update the README.md with the specific invocation command to create the bridge files in this template. I tested it on my own machine and it worked great.
