### ISSUE TITLE
What about plugins ?

### ISSUE THREAD

**Issue by Pierre-Monier** [Desdaemon/flutter_rust_bridge_template#22]
Hi, this template is really cool and save us a lot of time.

I'm currently trying to turn a project, made with this template, into a dart:ffi plugin.
Is there any guide or documentation or tips to do it ? This looks like a lot of tricky configurations to do, and I'm kind of lost.

Also, I think that it would be just perfect to have a plugin template out of the box

**Comment by Desdaemon** [comment]
Thank you for your kind words! There was [some interest](https://github.com/fzyzcjy/flutter_rust_bridge/issues/531) a few months ago on making a FFI plugin template, sadly I've not had time to follow up on this. I also haven't been using Flutter recently, but otherwise would be glad to review PRs either on this repo or the codegen's.

**Comment by Pierre-Monier** [comment]
Ok I see, I will work on creating a ffi plugin template. Maybe I can also update the docs on the codegen package if I got interesting things to add

**Comment by Pierre-Monier** [comment]
I think I will start from the macos-static branch, because it's what works on macos for me. 

Is there a reason to not merge this branch into master ?

**Comment by Desdaemon** [comment]
> I think I will start from the macos-static branch, because it's what works on macos for me. 
> 
> Is there a reason to not merge this branch into master ? 

Not much, other than that I (or someone else) will have to update the documentation to match.

**Comment by Pierre-Monier** [comment]
[I made this branch](https://github.com/Pierre-Monier/flutter_rust_bridge_template/tree/plugin) on my forked version of this repo. This is a v1 template for plugin development, currently works on android/ios/macos. 

Should I push in this repo on a specific plugin branch ? Or should I keep it on my side and rename it "flutter_rust_bridge_plugin_template" ? Not sure what's best

**Comment by Desdaemon** [comment]
Looks great! Could you create a PR against the [plugin](desdaemon/flutter_rust_bridge_template/tree/plugin) branch? I'll update the documentation to point to it.

**Comment by Pierre-Monier** [comment]
Also, [here is a plugin](https://github.com/Pierre-Monier/voronoi_diagram) make with the plugin template

**Comment by Desdaemon** [comment]
> Note that currently the ios/macos libraries are way too big and can't be published on pub.dev

This was also mentioned in part in the original issue as well. Perhaps we can leave it as a possible future contribution, and put in some documentation on this limitation and possible workarounds.

**Comment by Pierre-Monier** [comment]
I manage to fit my plugins to pass it under the pub.dev size limit. Basically, the tip is to use dynamic libraries whenever it's possible. I will update the template soon
