### ISSUE TITLE
How to change app name when using this template? 

### ISSUE THREAD

**Issue by dbsxdbsx** [Desdaemon/flutter_rust_bridge_template#29]
The app name means the display name for all platforms(windows, android...).  When in windows desktop, it also refers to the name displayed in task manager.

Currently, I found a  package called [rename](https://pub.dev/packages/rename), which  seems to have no effect, be it in android or windows.

And what I could do successfully is just changing the app UI title on win10, with advice [here](https://stackoverflow.com/questions/64800455/how-to-change-app-icon-and-app-name-for-flutter-desktop-application#:~:text=To%20change%20application%20icon%3A%20Simply,your%20application%20name%20inside%20window.). But still with this,  the app name displayed in the task manager is not changed.

So I wonder whether there is a way to change app name easily. It would be even better if doing so with just a single command, and then changing app name for all platforms.

**Comment by Desdaemon** [comment]
This is beyond the scope of this template, but you might be looking for [nativeshell](https://pub.dev/packages/nativeshell).
