### ISSUE TITLE
Xcode not found for -lnative_static

### ISSUE THREAD

**Issue by fermetin** [Desdaemon/flutter_rust_bridge_template#32]
Hello Iam using this template but I got error when trying to build on Mac/IOS env.

After i clone the repo, run the `flutter_rust_bridge_codegen` generate command then the flutter run for IOS 13;

As a result I got 

> `Failed to build iOS app
> Error (Xcode): Library not found for -lnative_static
> 
> 
> Could not build the application for the simulator.
> Error launching application on iPhone 13.`

Could not fix.

I tought flutter 3.6 not supported is it possible ?

flutter doctor
> [✓] Flutter (Channel master, 3.6.0-5.0.pre.12, on macOS 12.3 21E230 darwin-x64, locale en-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
• No issues found!

**Comment by Desdaemon** [comment]
This template is only tested against the stable branch of Flutter, though this might indicate a future breakage.
