### ISSUE TITLE
`flutter run -d chrome` produces CORS errors

### ISSUE THREAD

**Issue by coder0xff** [Desdaemon/flutter_rust_bridge_template#33]
Hi, really great project. I'm having trouble running `flutter run -d chrome` with a fresh clone.

![image](https://user-images.githubusercontent.com/2261949/204112064-20273245-825b-4f4e-8982-35bca64d2839.png)

I tried to reproduce this with the default project from `flutter create foobar`, but chrome worked fine with it. I tried the answer at https://stackoverflow.com/a/70660912/395029 but there was no change.

**Comment by Desdaemon** [comment]
This is a limitation with `flutter run`, please check out [the docs](https://cjycode.com/flutter_rust_bridge/build_wasm.html) or [this link](https://cjycode.com/flutter_rust_bridge/template/setup_web.html) for some workarounds.

**Comment by dinbtechit** [comment]
Followed the instruction from [this link](https://cjycode.com/flutter_rust_bridge/template/setup_web.html) and got it working. Thank you @Desdaemon

**Comment by coder0xff** [comment]
I just had to run `flutter_rust_bridge_serve` instead.
