### ISSUE TITLE
android compilation error

### ISSUE THREAD

**Issue by xdd666t** [Desdaemon/flutter_rust_bridge_template#35]
Hi this project is great but i have some problems compiling android

- The ndk path is configured in the gradle.properties file
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/35656085/205957827-d46a608e-c18f-45d5-83bf-d83c432f674e.png">

- When compiling android, the following errors will be reported. Did I configure something less?

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:cargoBuildDebug'.
> Process 'command 'cargo'' finished with non-zero exit value 101

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:cargoBuildDebug'.
...
Caused by: org.gradle.process.internal.ExecException: Process 'command 'cargo'' finished with non-zero exit 
....
```

**Comment by Desdaemon** [comment]
It's hard to tell what went wrong without the errors from Cargo itself. As a preliminary measure, please check that cargo-ndk is up to date and try running it again.
