### ISSUE TITLE
[question] Is it possible to change rust code and hot reload the app?

### ISSUE THREAD

**Issue by onichandame** [Desdaemon/flutter_rust_bridge_template#36]
I want to put most of the business logic in the native code. So most changes happen in the rust side. It would greatly reduce the overhead of change-build-test loop if the debug app is automatically hot reloaded when the rust code is changed.
Is it possible to achieve this? Sorry to ask before trying myself because I am very noob on flutter.

**Comment by Desdaemon** [comment]
Short answer is not in the near future. Unlike Dart, Rust does not have any built-in mechanism for hot-reloading, and the few experiments that exist in this space right now are very complicated. I recommend reading [this blog post](https://fasterthanli.me/articles/so-you-want-to-live-reload-rust) from fasterthanlime if you want to take a glimpse of what's needed to bring hot-reload to Rust.

**Comment by onichandame** [comment]
Thanks! The source is very helpful
