### ISSUE TITLE
Justfile command failure

### ISSUE THREAD

**Issue by nataliepopescu** [Desdaemon/flutter_rust_bridge_template#41]
Hiya, I'm trying to get codegen for the stock template working. I'm working on Linux (Ubuntu 22.04) and believe I've set up everything correctly according to [the docs](https://cjycode.com/flutter_rust_bridge/template/setup.html). Running `just` fails at the `flutter_rust_bridge_codegen` command with the following error: 

```
error: --c-output's inputs should match --rust-input's length
```

The `flutter_rust_bridge_codegen` command in the [justfile](https://github.com/Desdaemon/flutter_rust_bridge_template/blob/main/justfile#L8) does indeed have two `--c-output` lines, and I've confirmed that removing either one of them resolves the error. But I imagine that both options are useful if I want to target both iOS and macOS simultaneously. Is there a simple fix for this?

Thanks!

**Comment by Desdaemon** [comment]
No problem, I was somewhat aware this would become an issue due to new features being implemented in the codegen. For now, you can delete one of the `c-output` lines and manually copy the other to the required location. I'll refresh the template again soon.

**Comment by nataliepopescu** [comment]
Sounds good, thank you!

**Comment by nataliepopescu** [comment]
Ah, seems like this can actually be fixed by using the `-e` / `--extra-c-output-path` flag like so:

```sh
... 
    --c-output macos/Runner/bridge_generated.h \
    --extra-c-output-path ios/Runner/ \
...
```

I've confirmed that this works on an iOS simulator running iOS 16.2, and can submit a patch for this if that's helpful.
